objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>Represents a youtube channel</description>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Channel__c/fields/ChannelYtbID__c.field-meta.xml
<CustomField>
    <fullName>ChannelYtbID__c</fullName>
    <description>The id of youtube channel</description>
    <label>ChannelYtbID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/IntegrationKeys__c/IntegrationKeys__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IntegrationKeys</label>
</CustomObject>

objects/IntegrationKeys__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <label>key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/IntegrationKeys__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/YoutubeIntegration__mdt/YoutubeIntegration__mdt.object-meta.xml
<CustomObject>
    <label>YoutubeIntegration</label>
    <pluralLabel>YoutubeIntegrations</pluralLabel>
</CustomObject>

force-app/main/default/objects/YoutubeIntegration__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YoutubeIntegrationSelector.cls
public class YoutubeIntegrationSelector 
{
    public class YoutubeIntegrationSelectorException extends Exception{}

    public static YoutubeIntegration__mdt getEndpoint(String developerName)
    {
        YoutubeIntegration__mdt mdt = [SELECT Id, DeveloperName, Method__c, Endpoint__c FROM YoutubeIntegration__mdt WHERE DeveloperName =: developerName LIMIT 1];
        
        if(mdt == null) { throw new YoutubeIntegrationSelectorException('Registro de metadado não encontrado para esta integração'); }
        return mdt;
    }

    public static IntegrationKeys__c getIntegrationKey()
    {
        IntegrationKeys__c key = [SELECT key__c, name__c FROM IntegrationKeys__c WHERE name__c = 'YoutubeIntegration'];

        if(key == null) { throw new YoutubeIntegrationSelectorException('Registro de custom setting não encontrado para esta integração'); }
        return key;
    }
    
    public static List<Channel__c> getChannelsByID(Set<Id> ids)
    {
        return [SELECT Id, ChannelYtbID__c FROM Channel__c WHERE Id IN : ids];
    }

    public static List<Channel__c> getChannelsByYtbID(Set<String> ids)
    {
        return [SELECT Id, ChannelYtbID__c FROM Channel__c WHERE ChannelYtbID__c IN : ids];
    }
}