objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>Represents a youtube channel</description>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Channel__c/fields/ChannelYtbID__c.field-meta.xml
<CustomField>
    <fullName>ChannelYtbID__c</fullName>
    <description>The id of youtube channel</description>
    <label>ChannelYtbID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <displayFormat>VID-{00000}</displayFormat>
        <label>Video Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Video__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SearchVideoService.cls
public without sharing class SearchVideoService 
{
    public List<Video__c> searchVideos(String searchParam, String channelId)
    {
        // Lista de videos encontrados conforme o parâmetro de pesquisa
        List<Video__c> foundVideoList = new List<Video__c>();
        
        // Seleciona o canal que está envolvido na pesquisa
        Channel__c channelRecord = YoutubeIntegrationSelector.getChannelsByID(new Set<Id> { Id.valueOf(channelId) })[0];

        try
        {
            HttpResponse response = YoutubeIntegrationRequest.searchVideoListByParam(searchParam, channelRecord.ChannelYtbID__c);
            if(response.getStatusCode() != 200) { throw new YoutubeIntegrationRequest.YoutubeIntegrationRequestException('Callout request error. Method: SearchVideos, Status Code: ' + response.getStatusCode()); }

            YoutubeIntegrationSearchWrapper searchData = YoutubeIntegrationSearchWrapper.parse(response.getBody());

            // Associa cada item da pesquisa com o objeto Video__c
            for(YoutubeIntegrationSearchWrapper.Item item : searchData.items)
            {
                VideoDomain videoFromResponse = new VideoDomain();
                videoFromResponse.constructVideoFromWrapper(item);

                videoFromResponse.videoRecord.Channel__r = channelRecord;

                foundVideoList.add(videoFromResponse.videoRecord);
            }       

            // Retorna a lista de videos
            return foundVideoList;
        }
        catch (Exception e)
        {
            System.debug(e.getMessage());
            return null;
        }
    }
}