objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>Represents a youtube channel</description>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Channel_URL__c.field-meta.xml
<CustomField>
    <fullName>Channel_URL__c</fullName>
    <description>The url of youtube channel</description>
    <label>Channel URL</label>
    <type>Url</type>
</CustomField>

objects/Channel__c/fields/ChannelYtbID__c.field-meta.xml
<CustomField>
    <fullName>ChannelYtbID__c</fullName>
    <description>The id of youtube channel</description>
    <label>ChannelYtbID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Channel__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of youtube channel</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Channel__c/fields/Subscriber_Counts__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_Counts__c</fullName>
    <description>Number of subscribers in the youtube channel</description>
    <label>Subscriber Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Channel__c/fields/Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail__c</fullName>
    <description>The thumbnail of youtube channel</description>
    <label>Thumbnail</label>
    <type>Url</type>
</CustomField>

objects/Channel__c/fields/Video_Counts__c.field-meta.xml
<CustomField>
    <fullName>Video_Counts__c</fullName>
    <description>The number of videos from Youtube channel</description>
    <label>Video Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/View_Counts__c.field-meta.xml
<CustomField>
    <fullName>View_Counts__c</fullName>
    <label>View Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChannelDomain.cls
public class ChannelDomain 
{
    public Channel__c channelRecord{get; private set;}

    public void constructChannelFromWrapper(YoutubeIntegrationWrapper.Item item)
    {
        Channel__c channel = new Channel__c();

        if(item.snippet != null)
        {
            channel.Name = item.snippet.title;
            channel.Channel_URL__c = 'https://youtube.com/channel/' + item.snippet.channelId;
            channel.ChannelYtbID__c = item.snippet.channelId;
            channel.Description__c = item.snippet.description;
            channel.Thumbnail__c = item.snippet.thumbnails.get('default').get('url');
        }

        if(item.statistics != null)
        {
            channel.ChannelYtbID__c = item.customChannelId;
            channel.Subscriber_Counts__c = item.statistics.subscriberCount;
            channel.Video_Counts__c = item.statistics.videoCount;
            channel.View_Counts__c = item.statistics.viewCount;
        }

        this.channelRecord = channel;
    }
}