objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>Represents a youtube channel</description>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Channel__c/fields/ChannelYtbID__c.field-meta.xml
<CustomField>
    <fullName>ChannelYtbID__c</fullName>
    <description>The id of youtube channel</description>
    <label>ChannelYtbID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <displayFormat>VID-{00000}</displayFormat>
        <label>Video Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Video__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VideosFromChannelsBatchable.cls
public class VideosFromChannelsBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    public Set<String> channelIds {
        get
        {
            if(this.channelIds == null) { this.channelIds = new Set<String>(); }
                
            return this.channelIds;
        }
        private set;
    }

    public VideosFromChannelsBatchable(Set<String> channelIds)
    {
        this.channelIds = channelIds;
    }

    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator([SELECT Id, ChannelYtbID__c FROM Channel__c WHERE ChannelYtbID__c IN : this.channelIds]);
    }

    public void execute(Database.BatchableContext bc, List<Channel__c> scope)
    {
        List<Video__c> videoToInsertList = new List<Video__c>();

        for(Channel__c channel : scope)
        {
            HttpResponse response = YoutubeIntegrationRequest.getVideoListByChannelId(channel.ChannelYtbId__c);
            if(response.getStatusCode() != 200) { throw new YoutubeIntegrationRequest.YoutubeIntegrationRequestException('Callout request error. Method: VideoListByChannelId, Status Code: ' + response.getStatusCode()); }
        
            YoutubeIntegrationSearchWrapper wrappedResponse = YoutubeIntegrationSearchWrapper.parse(response.getBody());
            
            for(YoutubeIntegrationSearchWrapper.Item responseVideoItem : wrappedResponse.items)
            {
                VideoDomain videoFromResponse = new VideoDomain().constructVideoFromWrapper(responseVideoItem, channel.Id);
                videoToInsertList.add(videoFromResponse.videoRecord);
            }
        }

        insert videoToInsertList;
    }

    public void finish(Database.BatchableContext bc)
    {
        AsyncApexJob info = [SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id=:bc.getJobID()];
        System.debug('VideosFromChannelsBatchable - AsyncApexJob: ' + info);
        System.debug('Videos inserted.');
    }
}