objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>Represents a youtube channel</description>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Channel__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of youtube channel</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Channel__c/fields/Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail__c</fullName>
    <description>The thumbnail of youtube channel</description>
    <label>Thumbnail</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <displayFormat>VID-{00000}</displayFormat>
        <label>Video Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Video__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Video__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Video__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <label>Publish_Date</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Video__c/fields/Video_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_URL__c</fullName>
    <label>Video_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Video__c/fields/VideoYtbId__c.field-meta.xml
<CustomField>
    <fullName>VideoYtbId__c</fullName>
    <label>VideoYtbID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VideoDomain.cls
public class VideoDomain 
{
   public Video__c videoRecord{get; set;}

   public VideoDomain constructVideoFromWrapper(YoutubeIntegrationAbstractItem item, String channelId)
   {
       Video__c video = new Video__c();

       if(item.getSnippet())
       {
           // search result
           System.debug('Video Domain - construct from snippet');
           YoutubeIntegrationSearchWrapper.Item searchItem = (YoutubeIntegrationSearchWrapper.Item) item;

           video.VideoYtbId__c = searchItem.id.get('videoId');
           video.Name = searchItem.snippet.title;
           video.Video_URL__c = 'https://youtube.com/video/' + searchItem.id.get('videoId');
           video.Channel__c = channelId;
           video.Publish_Date__c = searchItem.snippet.publishedAt;
           video.Description__c = searchItem.snippet.description;
           video.Thumbnail__c = searchItem.snippet.thumbnails.get('default').get('url');
       }

       if(item.getStatictics())
       {
           // result statistics
           System.debug('Video Domain - construct from statistics');
       }

       this.videoRecord = video;

       return this;
   }
}